---
format: 
  revealjs:
    slide-number: true
    code-link: true
    highlight-style: a11y
    chalkboard: true
    # self-contained: true
    # scrollable: true
    theme: "meds_themes.scss"
---

## {#topicos data-menu-title="Tópicos"}

[Introdução]{.slide-title}

<hr>

::: {.body-text-m}
- Criação da PNAD
- Renovação para PNADC
- Diferenças entre PNAD e PNADC
- Forma de seleção da amostra na PNADC
- Conquistas da PNAD/PNADC
- Conceitos da PNADc
- Variávieis da PNADc
-É possível a análise conjunta entre PNAD e a PNADc
-
:::

---

[Introdução]{.slide-title}

[Criação da PNAD]{.custom-subtitle2}

<hr>

::: {.body-text-m}
- Criada em 1967 pelo **IBGE**.

- O Publico alvo era os cidadãos residentes em domicílios.

- Buscava informações a respeito da saúde, demografia, educação, indíces socioeconômicos e trabalho em todo o Brasil.
:::

---

[Introdução]{.slide-title}

[Renovação para PNADC]{.custom-subtitle2}

<hr>

::: {.body-text-m}
- Ocorre em 2012.

- Mudança na periodicidade da pesquisa.

- Lidava melhor com a sazonalidade e mudanças momentâneas nos domicílios.

:::


---


[Introdução]{.slide-title}

[Diferenças entre PNAD e PNADC]{.custom-subtitle2}

<hr>

::: {.body-text-m}
- PNAD desenvolvia índices anuais enquanto a PNADC desenvolve índices trimestrais.

- Metodologia.

- PNADC segue atualmente, focada em buscar informações sobre a força de trabalho brasileira.

- Tecnologia

:::

---

[Introdução]{.slide-title}

[Forma de seleção da amostra na PNADC]{.custom-subtitle2}

<hr>

::: {.body-text-m}
- Setor Censitário.

- Unidade Primária de Amostragem **(UPA)**.

- Estratifição,  Por Conglomerados e Amostragem Aleatória Simples.


:::

---

[Introdução]{.slide-title}

[Conquistas da PNAD/PNADC]{.custom-subtitle2}

<hr>

::: {.body-text-m}
- Estatuto da Criança e do Adolescente **(ECA - 1990)**.

- Programa Bolsa Familia **(2003)**.

- "Minha casa minha vida" **(2009)**.

- Artigos Científicos

:::
